/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE__mcdp__variable__baseframe
#define __PYX_HAVE__mcdp__variable__baseframe

#include "Python.h"
struct DpFrameObject;
struct DpVariableObject;

/* "mcdp/variable/baseframe.pxd":30
 * 
 * 
 * cdef api class BaseFrame(McdpObject) [object DpFrameObject, type DpFrame_Type]:             # <<<<<<<<<<<<<<
 *     cdef:
 *         dict __dict__
 */
struct DpFrameObject {
  struct DpBaseObject __pyx_base;
  struct __pyx_vtabstruct_4mcdp_8variable_9baseframe_BaseFrame *__pyx_vtab;
  PyObject *__dict__;
  struct DpSelectorObject *frame_selector;
  struct __pyx_obj_4mcdp_7objects_BaseNamespace *namespace;
  PyObject *name_pools;
  uint8_t flag;
};

/* "mcdp/variable/baseframe.pxd":40
 * 
 * 
 * cdef api class FrameVariable(McdpObject) [object DpVariableObject, type DpVariable_Type]:             # <<<<<<<<<<<<<<
 *     cdef:
 *         bint special_name
 */
struct DpVariableObject {
  struct DpBaseObject __pyx_base;
  struct __pyx_vtabstruct_4mcdp_8variable_9baseframe_FrameVariable *__pyx_vtab;
  int special_name;
  PyObject *name;
  struct DpFrameObject *frame;
  Py_ssize_t channel_id;
};

#ifndef __PYX_HAVE_API__mcdp__variable__baseframe

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__mcdp__variable__baseframe */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbaseframe(void);
#else
/* WARNING: Use PyImport_AppendInittab("baseframe", PyInit_baseframe) instead of calling PyInit_baseframe directly from Python 3.5 */
PyMODINIT_FUNC PyInit_baseframe(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"baseframe\", PyInit_baseframe) instead of calling PyInit_baseframe directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"baseframe\", PyInit_baseframe) instead of calling PyInit_baseframe directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"baseframe\", PyInit_baseframe) instead of calling PyInit_baseframe directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_baseframe_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_baseframe() __PYX_WARN_IF_PyInit_baseframe_INIT_CALLED(PyInit_baseframe())
#endif
#endif

#endif /* !__PYX_HAVE__mcdp__variable__baseframe */
