/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE_API__mcdp__variable__console
#define __PYX_HAVE_API__mcdp__variable__console
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"
#include "console.h"

static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_Tell)(PyObject *, PyObject *) = 0;
#define DpConsole_Tell __pyx_api_f_4mcdp_8variable_7console_DpConsole_Tell
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_TellString)(PyObject *, char const *) = 0;
#define DpConsole_TellString __pyx_api_f_4mcdp_8variable_7console_DpConsole_TellString
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_Print)(PyObject *) = 0;
#define DpConsole_Print __pyx_api_f_4mcdp_8variable_7console_DpConsole_Print
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_PrintString)(char const *) = 0;
#define DpConsole_PrintString __pyx_api_f_4mcdp_8variable_7console_DpConsole_PrintString
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_Title)(PyObject *, enum MCTitle_TypeFlag, PyObject *) = 0;
#define DpConsole_Title __pyx_api_f_4mcdp_8variable_7console_DpConsole_Title
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_Show)(enum MCTitle_TypeFlag, PyObject *) = 0;
#define DpConsole_Show __pyx_api_f_4mcdp_8variable_7console_DpConsole_Show
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_ShowString)(enum MCTitle_TypeFlag, char const *) = 0;
#define DpConsole_ShowString __pyx_api_f_4mcdp_8variable_7console_DpConsole_ShowString
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleReset)(PyObject *) = 0;
#define DpConsole_TitleReset __pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleReset
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleClear)(PyObject *) = 0;
#define DpConsole_TitleClear __pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleClear
static int (*__pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleSetTime)(PyObject *, int, int, int) = 0;
#define DpConsole_TitleSetTime __pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleSetTime
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_mcdp__variable__console(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("mcdp.variable.console");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_Tell", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_Tell, "int (PyObject *, PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_TellString", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_TellString, "int (PyObject *, char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_Print", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_Print, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_PrintString", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_PrintString, "int (char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_Title", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_Title, "int (PyObject *, enum MCTitle_TypeFlag, PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_Show", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_Show, "int (enum MCTitle_TypeFlag, PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_ShowString", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_ShowString, "int (enum MCTitle_TypeFlag, char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_TitleReset", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleReset, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_TitleClear", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleClear, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "DpConsole_TitleSetTime", (void (**)(void))&__pyx_api_f_4mcdp_8variable_7console_DpConsole_TitleSetTime, "int (PyObject *, int, int, int)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__mcdp__variable__console */
