/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE__mcdp__objects
#define __PYX_HAVE__mcdp__objects

#include "Python.h"
struct DpBaseObject;

/* "mcdp/objects.pxd":4
 * 
 * 
 * ctypedef api object (*T_property)(object nsp)             # <<<<<<<<<<<<<<
 * 
 * 
 */
typedef PyObject *(*T_property)(PyObject *);

/* "mcdp/objects.pxd":7
 * 
 * 
 * cdef api class McdpObject(object) [object DpBaseObject, type DpBaseObject_Type]:             # <<<<<<<<<<<<<<
 *     pass
 * 
 */
struct DpBaseObject {
  PyObject_HEAD
};

#ifndef __PYX_HAVE_API__mcdp__objects

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__mcdp__objects */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initobjects(void);
#else
/* WARNING: Use PyImport_AppendInittab("objects", PyInit_objects) instead of calling PyInit_objects directly from Python 3.5 */
PyMODINIT_FUNC PyInit_objects(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"objects\", PyInit_objects) instead of calling PyInit_objects directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"objects\", PyInit_objects) instead of calling PyInit_objects directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"objects\", PyInit_objects) instead of calling PyInit_objects directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_objects_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_objects() __PYX_WARN_IF_PyInit_objects_INIT_CALLED(PyInit_objects())
#endif
#endif

#endif /* !__PYX_HAVE__mcdp__objects */
