/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE__mcdp__variable__selector
#define __PYX_HAVE__mcdp__variable__selector

#include "Python.h"
struct DpSelectorObject;

/* "mcdp/variable/selector.pxd":6
 * 
 * 
 * cdef api class Selector(McdpObject) [object DpSelectorObject, type DpSelector_Type]:             # <<<<<<<<<<<<<<
 *     cdef dict _args "arguments"
 *     cdef readonly str name
 */
struct DpSelectorObject {
  struct DpBaseObject __pyx_base;
  struct __pyx_vtabstruct_4mcdp_8variable_8selector_Selector *__pyx_vtab;
  PyObject *arguments;
  PyObject *name;
};

#ifndef __PYX_HAVE_API__mcdp__variable__selector

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__mcdp__variable__selector */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initselector(void);
#else
/* WARNING: Use PyImport_AppendInittab("selector", PyInit_selector) instead of calling PyInit_selector directly from Python 3.5 */
PyMODINIT_FUNC PyInit_selector(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"selector\", PyInit_selector) instead of calling PyInit_selector directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"selector\", PyInit_selector) instead of calling PyInit_selector directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"selector\", PyInit_selector) instead of calling PyInit_selector directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_selector_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_selector() __PYX_WARN_IF_PyInit_selector_INIT_CALLED(PyInit_selector())
#endif
#endif

#endif /* !__PYX_HAVE__mcdp__variable__selector */
