from typing import Any, AnyStr, Final, Literal, Optional


def mkdir(dir_path: str) -> None:...

class Stream:
    path: Final[str]

    def __init__(self, path: str, *, root: Optional[str] = None) -> None:...
    def open(self, mod: Literal['w', 'a'] = 'w') -> None:...
    def write(self, data: AnyStr) -> int:...
    def dump(self, data: Any) -> int:...
    def close(self) -> None:...
    def writable(self) -> bool:...
    @property
    def closed(self) -> bool:...
    def __enter__(self) -> "Stream":...
    def __exit__(self, exc_type, exc_ins, traceback) -> None:...