/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE_API__mcdp__context
#define __PYX_HAVE_API__mcdp__context
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static void (*__pyx_api_f_4mcdp_7context_dp_insert)(char const *) = 0;
#define dp_insert __pyx_api_f_4mcdp_7context_dp_insert
static void (*__pyx_api_f_4mcdp_7context_dp_comment)(char const *) = 0;
#define dp_comment __pyx_api_f_4mcdp_7context_dp_comment
static void (*__pyx_api_f_4mcdp_7context_dp_commentline)(char const *, ...) = 0;
#define dp_commentline __pyx_api_f_4mcdp_7context_dp_commentline
static void (*__pyx_api_f_4mcdp_7context_dp_newline)(int) = 0;
#define dp_newline __pyx_api_f_4mcdp_7context_dp_newline
static void (*__pyx_api_f_4mcdp_7context_dp_fastAddTag)(char const *) = 0;
#define dp_fastAddTag __pyx_api_f_4mcdp_7context_dp_fastAddTag
static void (*__pyx_api_f_4mcdp_7context_dp_addTag)(PyObject *, PyObject *, PyObject *) = 0;
#define dp_addTag __pyx_api_f_4mcdp_7context_dp_addTag
static void (*__pyx_api_f_4mcdp_7context_dp_enter)(PyObject *, PyObject *, PyObject *) = 0;
#define dp_enter __pyx_api_f_4mcdp_7context_dp_enter
static void (*__pyx_api_f_4mcdp_7context_dp_fastEnter)(char const *) = 0;
#define dp_fastEnter __pyx_api_f_4mcdp_7context_dp_fastEnter
static void (*__pyx_api_f_4mcdp_7context_dp_exit)(void) = 0;
#define dp_exit __pyx_api_f_4mcdp_7context_dp_exit
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_mcdp__context(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("mcdp.context");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "dp_insert", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_insert, "void (char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_comment", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_comment, "void (char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_commentline", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_commentline, "void (char const *, ...)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_newline", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_newline, "void (int)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_fastAddTag", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_fastAddTag, "void (char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_addTag", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_addTag, "void (PyObject *, PyObject *, PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_enter", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_enter, "void (PyObject *, PyObject *, PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_fastEnter", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_fastEnter, "void (char const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "dp_exit", (void (**)(void))&__pyx_api_f_4mcdp_7context_dp_exit, "void (void)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__mcdp__context */
