/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE__mcdp__dp_interface
#define __PYX_HAVE__mcdp__dp_interface

#include "Python.h"

/* "mcdp/dp_interface.pyx":4
 * 
 * 
 * ctypedef api object (*T_pFactory)(BaseNamespace nsp)             # <<<<<<<<<<<<<<
 * 
 * cdef api inline void DpNsp_property(const char* name, T_pFactory factory) except *:
 */
typedef PyObject *(*T_pFactory)(struct __pyx_obj_4mcdp_7objects_BaseNamespace *);

#ifndef __PYX_HAVE_API__mcdp__dp_interface

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__mcdp__dp_interface */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdp_interface(void);
#else
/* WARNING: Use PyImport_AppendInittab("dp_interface", PyInit_dp_interface) instead of calling PyInit_dp_interface directly from Python 3.5 */
PyMODINIT_FUNC PyInit_dp_interface(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"dp_interface\", PyInit_dp_interface) instead of calling PyInit_dp_interface directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"dp_interface\", PyInit_dp_interface) instead of calling PyInit_dp_interface directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"dp_interface\", PyInit_dp_interface) instead of calling PyInit_dp_interface directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_dp_interface_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_dp_interface() __PYX_WARN_IF_PyInit_dp_interface_INIT_CALLED(PyInit_dp_interface())
#endif
#endif

#endif /* !__PYX_HAVE__mcdp__dp_interface */
